"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1000, 750)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # oblique wall 0
    wall = NormalWall(pos_start=(-130, 379),
                      pos_end=(-119, -168))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 1
    wall = NormalWall(pos_start=(-118, 379),
                      pos_end=(-107, -177))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-349, -159),
                      pos_end=(-349, -177))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 3
    wall = NormalWall(pos_start=(-349, -163),
                      pos_end=(-119, -163))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(58, -163),
                      pos_end=(58, -181))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 5
    wall = NormalWall(pos_start=(58, -166),
                      pos_end=(503, -166))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(-352, -174),
                      pos_end=(-110, -174))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(55, -178),
                      pos_end=(503, -178))
    playground.add(wall, wall.wall_coordinates)

