"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1819, 1350)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-891, 664),
                      pos_end=(-891, -658))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(-890, 661),
                      pos_end=(890, 661))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(886, 663),
                      pos_end=(886, -658))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(-292, 260),
                      pos_end=(-292, -103))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 4
    wall = NormalWall(pos_start=(-414, -99),
                      pos_end=(-290, -99))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(-411, -97),
                      pos_end=(-411, -659))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(-292, 257),
                      pos_end=(218, 257))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 7
    wall = NormalWall(pos_start=(214, 259),
                      pos_end=(214, -104))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 8
    wall = NormalWall(pos_start=(-198, -100),
                      pos_end=(217, -100))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 9
    wall = NormalWall(pos_start=(-197, -99),
                      pos_end=(-148, -99))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = NormalWall(pos_start=(-153, -99),
                      pos_end=(-153, -659))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = NormalWall(pos_start=(-316, -219),
                      pos_end=(-150, -219))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 12
    wall = NormalWall(pos_start=(-316, -221),
                      pos_end=(-150, -221))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 13
    wall = NormalWall(pos_start=(-414, -332),
                      pos_end=(-250, -332))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 14
    wall = NormalWall(pos_start=(-414, -334),
                      pos_end=(-252, -334))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(-341, -331),
                      pos_end=(-341, -557))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(-338, -332),
                      pos_end=(-338, -557))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(-255, -433),
                      pos_end=(-255, -657))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(-252, -433),
                      pos_end=(-252, -657))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = NormalWall(pos_start=(-414, -653),
                      pos_end=(-150, -653))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(-894, -654),
                      pos_end=(888, -654))
    playground.add(wall, wall.wall_coordinates)

